#pragma once
#include <algorithm>
#include <chrono>
#include <format>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <list>
#include <map>
#include <nlohmann/json.hpp>
#include <regex>
#include <sstream>
#include <string>
#include <tuple>
#include <type_traits>
#include <vector>
#include "EMessageType.h"
#include "ESeason.h"

using nlohmann::json;
using std::string;
using std::vector;
using std::tm;
using std::stringstream;
using std::chrono::hh_mm_ss;
using std::chrono::time_point;
using std::chrono::sys_time;
using std::chrono::milliseconds;
using std::map;
using std::shared_ptr;
using std::make_shared;
using std::tuple;
using std::cout;
using std::ifstream;
using std::ofstream;
using std::format;
using std::list;
using std::regex;